FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    python3-dev \
    ncbi-blast+ \
    vsearch && \
    rm -rf /var/lib/apt/lists/*

RUN pip install crest4==4.4.5

# Set environment variable
WORKDIR crest4
RUN mkdir .crest4
ENV CREST4_DIR=/crest4/.crest4
