FROM debian:bookworm-slim

LABEL maintainer="Haris Zafeiropoulos <haris.zafeiropoulos@atomicmail.io>"

# venv required since debian
RUN apt-get update && apt-get install -y \
    wget \
    python3 \
    python3-venv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

# Add and fix scripts location
WORKDIR /opt/pema
COPY scripts/ scripts/
RUN chmod +x scripts/*.sh scripts/*.py

# Add scripts folder to PATH
ENV PATH="/opt/pema/scripts:${PATH}"

# Create virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Upgrade pip in the venv
# RUN pip install 
# --no-cache-dir --upgrade pip

# Install Python packages  # --no-cache-dir \
RUN pip install \
    pandas \
    numpy

RUN apt-get update && apt-get install -y \
    vim \
    gawk \
    bc
# To build the image, run:
# docker build -f Dockerfile.pema_nf -t hariszaf/pema-nf:0.1.0 ~/github_repos/HCMR/pema/