# FROM alpine:latest
FROM eclipse-temurin:8-jre-jammy

# Environment variables
ENV INSTALL_DIR=/opt
# There is 2.14 version available, but PEMA uses 2.13-trained databases
ENV RDPCLASSIFIER=2.13
ENV RDP_PEMA=https://zenodo.org/records/16876159/files/rdp_dbs_v220.tar.gz
ENV SHELL_CONFIG=/root/.bashrc

# Install utilities
RUN apt-get update && apt-get install -y \
    wget curl unzip tar && \
    rm -rf /var/lib/apt/lists/*

# Install RDP Classifier
WORKDIR $INSTALL_DIR
RUN wget -O rdp_classifier_$RDPCLASSIFIER.zip "https://sourceforge.net/projects/rdp-classifier/files/rdp-classifier/rdp_classifier_$RDPCLASSIFIER.zip/download" && \
    unzip rdp_classifier_$RDPCLASSIFIER.zip && \
    rm rdp_classifier_$RDPCLASSIFIER.zip && \
    echo "export PATH=\"$INSTALL_DIR/rdp_classifier_$RDPCLASSIFIER/:\$PATH\"" >> $SHELL_CONFIG

# Set workidir to RDP Classifier directory to download PEMA trained databases
WORKDIR $INSTALL_DIR/rdp_classifier_$RDPCLASSIFIER
# Download PEMA-trained databases
RUN curl -L \
    --retry 10 \
    --retry-delay 5 \
    --retry-connrefused \
    -C - \
    -o rdp_dbs_v220.tar.gz \
    $RDP_PEMA

# RUN tar -zxvf rdp_dbs_v220.tar.gz && \
#     mv -f TRAIN/ $INSTALL_DIR/rdp_classifier_$RDPCLASSIFIER/TRAIN/ && \
#     rm rdp_dbs_v220.tar.gz

WORKDIR $INSTALL_DIR

# # -----------------
# # Install RDP Classifier
# # -----------------
# if [[ -x $INSTALL_DIR/rdp_classifier_$RDPCLASSIFIER ]]; then

#   echo -e "$GREEN_TICK RDP Classifier is already installed"

# else

#   echo -e "$HOURGLASS RDP Classifier is being installed.. "
#   wget -L -O rdp_classifier_$RDPCLASSIFIER.zip "https://sourceforge.net/projects/rdp-classifier/files/rdp-classifier/rdp_classifier_$RDPCLASSIFIER.zip/download"
#   unzip rdp_classifier_$RDPCLASSIFIER.zip
#   # rm rdp_classifier_$RDPCLASSIFIER.zip

#   echo "export PATH=\"$INSTALL_DIR/rdp_classifier_$RDPCLASSIFIER/:\$PATH\"" >> $SHELL_CONFIG
#   echo -e "RDP Classifier has been installed $TADA"

# fi

# RDP_TRAIN_DIR="$INSTALL_DIR/rdp_classifier_$RDPCLASSIFIER/TRAIN"

# if [[ -d "$RDP_TRAIN_DIR" ]] && [ "$(ls -A "$RDP_TRAIN_DIR")" ]; then

#   echo -e "$GREEN_TICK PEMA trained databases to be use with RDP Classifier have been already retrieved." 

# else

#   echo -e "$HOURGLASS Download PEMA trained RDP databases..."

#   cd rdp_classifier_$RDPCLASSIFIER/

#   curl -L -o rdp_dbs_v220.tar.gz -L $RDP_PEMA
#   tar -zxvf rdp_dbs_v220.tar.gz
#   mv -f TRAIN/ $RDP_TRAIN_DIR/
#   # rm rdp_dbs_v220.tar.gz

#   echo -e "PEMA trained RDP databases were retrieved $TADA"
# fi
