# PEMA: a flexible Pipeline for Environmental DNA Metabarcoding Analysis 
# of the 16S/18S ribosomal RNA, ITS, and COI marker genes. GigaScience. 2020 Mar;9(3):giaa022.
# 
# Aim:   Build PEMA Docker image based on the `pemabase` one 
# 
# Usage: docker build -t hariszaf/pemabase:<tag> .


FROM hariszaf/pemabase:v.2.1.2
LABEL maintainer = "Haris Zafeiropoulos" 
LABEL contact    = "haris.zafeiropoulos@kuleuven.be"
LABEL build_date = "2023-12-06"
LABEL version    = "v.2.1.5"


# Walk around so ncbi-taxonomist can be used in Singularity containers
RUN ln -s /opt/miniconda3/bin/ncbi-taxonomist /home/tools/ncbi-taxonomist

# Install fastp 
WORKDIR /usr/local/bin
RUN wget http://opengene.org/fastp/fastp && \
    chmod a+x ./fastp && \
    echo "export PATH=$PATH:/usr/bin/local/fastp"


# Set "home" as my working directory when a container starts
WORKDIR /home
RUN rm *tar.gz Miniconda3-latest-Linux-x86_64.sh &&\ 
    dpkg --list > pema_environment.tsv

RUN echo "R version running on PEMA" > pema_R_packages.tsv ; Rscript -e 'R.version'   >> pema_R_packages.tsv && \
    echo  "\n---------------------------------------\n"  >> pema_R_packages.tsv  && \
    echo  "\nR package along with its version: \n"       >> pema_R_packages.tsv  && \
    echo  "dplyr"          >> pema_R_packages.tsv ; Rscript -e 'packageVersion("dplyr")' >> pema_R_packages.tsv && \
    echo  "\nvegan"        >> pema_R_packages.tsv ; Rscript -e 'packageVersion("vegan")' >> pema_R_packages.tsv && \
    echo  "\ntidyr"        >> pema_R_packages.tsv ; Rscript -e 'packageVersion("tidyr")' >> pema_R_packages.tsv && \
    echo  "\nBiocManager"  >> pema_R_packages.tsv ; Rscript -e 'packageVersion("BiocManager")' >> pema_R_packages.tsv && \
    echo  "\nRColorBrewer" >> pema_R_packages.tsv ; Rscript -e 'packageVersion("RColorBrewer")' >> pema_R_packages.tsv && \
    echo  "\nphyloseq"     >> pema_R_packages.tsv ; Rscript -e 'packageVersion("phyloseq")' >> pema_R_packages.tsv && \
    echo  "\nShortRead"    >> pema_R_packages.tsv ; Rscript -e 'packageVersion("ShortRead")' >> pema_R_packages.tsv

# Copy and paste the manually written scripts that PEMA needs
WORKDIR /home/scripts
COPY /scripts/ ./
RUN chmod -R +777 /home/scripts

WORKDIR /home/modules
COPY /modules/ ./
RUN chmod -R +777 /home/modules

# Copy and paste the PEMA script!
WORKDIR /home
COPY pema_latest.bds .

## Make a source of the .bashrc file
WORKDIR /root
RUN echo "export PATH=$PATH:/home/tools/BDS/.bds" >> /root/.bashrc
RUN ["/bin/bash", "-c", "-l",  "source /root/.bashrc"]

RUN export PATH=$PATH:/home/tools/BDS/.bds
ENV PATH=$PATH:/home/tools/BDS/.bds
