FROM ubuntu:20.04 

LABEL maintainer = "Haris Zafeiropoulos" 
LABEL contact    = "haris-zaf@hcmr.gr"
LABEL build_date = "2024-07-22"
LABEL version    = "v2.2.0"


RUN apt-get update 
RUN apt-get install -y apt-transport-https && apt-get install -y vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
