FROM python:3.9-slim

RUN apt update && \ 
    apt install -y ncbi-blast+ && \ 
    apt install -y vsearch

RUN pip install crest4

# Set environment variable
WORKDIR crest4
RUN mkdir .crest4
ENV CREST4_DIR=/crest4/.crest4

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     gcc \
#     g++ \
#     make \
#     && rm -rf /var/lib/apt/lists/*
